### ISSUE TITLE
复现小问题

### ISSUE THREAD

**Issue by xylytx** [xiesicong/fpga_eth_dual_ov5640.srcs#1]
请问大佬可以给一下各个ip核的配置吗，想移植复现一下

**Comment by xiesicong** [comment]
你好，此工程是我在野火公司任职期间为板卡写的一个demo，目前我已不在野火。野火的资料均开源，如果你有需要，可以直接访问https://embedfire.com/，进入野火资料网站下载，如果网站失效，你可以百度搜索“野火开源资料下载”，里面有更多的学习资料和开源工程，本工程也在内，你可以直接使用ISE或Quartus II或VIVADO来打开工程，查看里面的IP核配置。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiesicong/fpga_eth_dual_ov5640"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 下午3:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xiesicong/fpga_eth_dual_ov5640] 复现小问题 (Issue #1)





 
请问大佬可以给一下各个ip核的配置吗，想移植复现一下

**Comment by xylytx** [comment]
感谢回复
